#!/bin/bash
set -e

function printhelp() {
    echo "Usage: ./app <command>"
    echo "Available commands:"
    echo "   (s)tart:         starts the server in production mode"
    echo "   (d)evelop:       starts the server for development"
    echo "   (u)pdate:        updates dependencies"
}

COMMAND=$1

if [ -z $COMMAND ]; then
  printhelp
fi

shift

if [[ $COMMAND == 's' || $COMMAND == 'start' ]]; then
	echo "loading in production mode..."
	source activate codenames
	gunicorn server:app --preload -b unix:/tmp/gunicorn.sock -w 4

elif [[ $COMMAND == 'd' || $COMMAND == 'develop' ]]; then
	echo "loading in dev mode..."
	source activate codenames
	gunicorn server:app --reload --preload -b 127.0.0.1:5000 -w 4

elif [[ $COMMAND == 'u' || $COMMAND == 'update' ]]; then
	conda env create -f=environment.yml --force

else
	echo "unknown command $COMMAND!"
	printhelp

fi
